name = "Jurodedu-Neoforged"
author = "Formuna"
version = "3.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1771c6aace2739cd3608d049ef230da58ed472d1e5aa4021383dd86d7144abf4"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.222"
